name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "dev"
      - "prod"
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Give permission to executables
        run: |
          chmod +x gradlew
          chmod +x ./.shell/publish_gen_to_maven_local.sh
      - run: ./gradlew test --info

  style:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code